version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: trendscout_postgres
    environment:
      POSTGRES_USER: trendscout
      POSTGRES_PASSWORD: trendscout
      POSTGRES_DB: trendscout
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/configs/sql/init-scripts:/docker-entrypoint-initdb.d
    restart: no

  mongo:
    image: mongo:6
    container_name: trendscout_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: trendscout
      MONGO_INITDB_ROOT_PASSWORD: trendscout
      MONGO_INITDB_DATABASE: trendscout
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: no

  redis:
    image: redis:7
    container_name: trendscout_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: no

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: trendscout_backend
    depends_on:
      - postgres
      - mongo
      - redis
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_USER=trendscout
      - DB_PASSWORD=trendscout
      - DB_NAME=trendscout
      - MONGO_URI=mongodb://trendscout:trendscout@mongo:27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=8080
      - JWT_SECRET=your_jwt_secret_key
      - GEMINI_API_KEY=your_gemini_api_key
    restart: no

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: trendscout_frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8080
    restart: no

volumes:
  postgres_data:
  mongo_data:
  redis_data:
